### ISSUE TITLE
button "load Data" stopped updating card configuration

### ISSUE THREAD

**Issue by Phos69** [daredoes/linked-lovelace-ui#38]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
core
2024.5.0

Supervisor
2024.04.4

Operating System
12.2

Frontend
20240501.0

**Last working release (if known):**
I suppose it was working with previous relase but cannot confirm

**Browser and Operating System:**
Chrome 124.0.6367.119 64bit
windows 11
I also tried on Android phone running companion version 2024.4.1-full and it does not work as well

**Description of problem:**

When changing a templated card, and then pressing the Load Data button from the LinkedLovelaceStatus Card to apply edits, I used to get a refresh page button that would refresh the configuration and apply all the new settings.
I am not getting that anymore and even after manually refreshing the webpage, the configuration on the cards does not update

**Javascript errors shown in the web inspector (if applicable):**
In the browser console, after activating the debug mode from the status I get the following messages when trying to update the card:

```
linked-lovelace-ui.js?hacstag=559360809222:59   LINKED-LOVELACE-UI   Backing up current dashboard data. Ignore 'Update' Messages. Dry-Run is enabled.    {timestamp: '2024-05-02T10:50:19.972Z'}
linked-lovelace-ui.js?hacstag=559360809222:82 Uncaught (in promise) {code: 'config_not_found', message: 'No config found.'}
Fr.handleClick @ linked-lovelace-ui.js?hacstag=559360809222:82
await in Fr.handleClick (async)
handleEvent @ linked-lovelace-ui.js?hacstag=559360809222:32


```
![image](https://github.com/daredoes/linked-lovelace-ui/assets/79162998/3ade9844-1fae-45d6-aea5-802b9ff6f2ff)
**Additional information:**

The cards were previously working as intended so I assume some recent updates broke it

Please let me know if you need any additional information

**Comment by daredoes** [comment]
@Phos69 Just merged 2.2.3 to help provide more clarity around this, and ideally fail silently in the background

**Comment by erkr** [comment]
Thanks for working on this issue. With v2.2.3 I lost both the partials and status card. During start up of HA there is an error in  HA log:
``` 
Logger: frontend.js.latest.202405010
Source: components/system_log/__init__.py:333
First occurred: 11:27:34 (1 occurrences)
Last logged: 11:27:34

Uncaught error from WebKit 605.1.15 on iOS 17.4.1 TypeError: undefined is not an object (evaluating '(void 0).diff=Lr') module code (/hacsfiles/linked-lovelace-ui/linked-lovelace-ui.js:72:10372)
```
I provided some screenshots on discord
Best Eric

**Comment by daredoes** [comment]
@erkr that's what I get for trying to update an import. Reverting that line, should fix the above bug. 2.2.4 will hopefully work

**Comment by Phos69** [comment]
Hi @daredoes,

thanks for working on it.

I attached the full logs I got from browser console

[linkedlovelace.log](https://github.com/daredoes/linked-lovelace-ui/files/15225284/linkedlovelace.log)

**Comment by daredoes** [comment]
Looks like it is the map config that seems to crash when creating a diff. I'll add some safety around the diffing process and see if that fixes it fast

**Comment by erkr** [comment]
@daredoes It works. The overview errors are still in the console log.

**Comment by daredoes** [comment]
Marking as resolved
